import { type FC } from 'react';

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title:       'Horus | Search location',
  description: 'Generated by create next app'
};

const LocationLayout: FC<{ children: React.ReactNode }> = ({ children }) => children;

export default LocationLayout;
